//PropertyUtility propUtil = new PropertyUtility();

//propUtil.newListedProperties();

//PropertyUtility.newListedProperties();

//Integer maxHomeValue = 2000000;
//List<Property__c> property = [SELECT Name, Price__c FROM Property__c WHERE Price__c < :maxHomeValue];

//System.debug(property);

//Declare the groceries list
List<String> groceries = new List<String>();
  
//The output for this statement is an empty list, ().
System.debug('Groceries Value: ' + groceries);